import operator
from typing_extensions import TypedDict,Annotated,Sequence
from langchain_core.messages import BaseMessage
from langgraph.graph import add_messages

class FullAgentInputState(TypedDict):
    messages: Annotated[Sequence[BaseMessage] , add_messages]

class FullAgentState(TypedDict , total = False):

    # The conversation between the user and the Scope Agent
    messages: Annotated[Sequence[BaseMessage] , add_messages]

    # Research brief generated by Scope Graph
    research_brief: str

    # Coordination messages from Supervisor 
    supervisor_messages: Annotated[Sequence[BaseMessage] , add_messages]

    # The number of iterations of the Supervisor
    research_iterations: int 

    research_limitations: list[str]
    termination_reason: str

    # Compression Research results of sub-research agents
    notes: Annotated[list[str], operator.add]

    # Raw Research results of sub-research agents
    raw_notes: Annotated[list[str], operator.add]

    # Final Report
    final_report: str

class FullAgentOutputState(TypedDict, total=False):
    """Full Agent 最终对外输出。"""

    messages: Annotated[
        Sequence[BaseMessage],
        add_messages,
    ]

    research_brief: str
    final_report: str
    notes: list[str]
    raw_notes: list[str]
    research_limitations: list[str]
    termination_reason: str
